# Generated by Django 2.1.7 on 2019-03-21 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('MC_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('id_shipper', models.IntegerField()),
                ('id_carrier', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='carrier.Carrier')),
            ],
        ),
    ]
