# Generated by Django 2.1.7 on 2019-04-16 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipper', '0001_initial'),
        ('carrier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejectedload',
            name='load',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipper.Load'),
        ),
        migrations.AddField(
            model_name='carrieruser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
