# Generated by Django 2.1.7 on 2019-04-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0002_auto_20190418_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrieruser',
            name='MC_number',
            field=models.IntegerField(verbose_name='MC number'),
        ),
    ]
