# Generated by Django 2.1.7 on 2019-03-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0002_auto_20190321_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='id_carrier',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
