# Generated by Django 2.1.7 on 2019-03-26 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0003_auto_20190326_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='pickup_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
