# Generated by Django 2.1.7 on 2019-04-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0005_auto_20190326_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_load', models.IntegerField()),
                ('id_carrier', models.IntegerField()),
            ],
        ),
    ]
