# Generated by Django 2.1.7 on 2019-03-20 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('mc_number', models.IntegerField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateTimeField()),
                ('ref', models.CharField(max_length=50)),
                ('origin_city', models.CharField(blank=True, max_length=500)),
                ('destionation_city', models.CharField(blank=True, max_length=500)),
                ('price', models.FloatField()),
                ('suggested_price', models.FloatField(blank=True)),
                ('carrier', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shipper.Carrier')),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='load',
            name='shipper',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shipper.Shipper'),
        ),
    ]
