# Generated by Django 2.1.7 on 2019-04-16 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carrier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateTimeField(blank=True, null=True)),
                ('ref', models.CharField(max_length=50)),
                ('origin_city', models.CharField(blank=True, max_length=500)),
                ('destination_city', models.CharField(blank=True, max_length=500)),
                ('price', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('suggested_price', models.FloatField(blank=True)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrier.CarrierUser')),
            ],
        ),
        migrations.CreateModel(
            name='ShipperUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipper_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='load',
            name='shipper',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shipper.ShipperUser'),
        ),
    ]
