# Generated by Django 2.1.7 on 2019-04-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='destination_city',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='load',
            name='origin_city',
            field=models.CharField(max_length=500),
        ),
    ]
