# Generated by Django 2.1.7 on 2019-03-27 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='load',
            name='shipper',
        ),
    ]
