# Generated by Django 2.1.7 on 2019-03-27 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0002_auto_20190327_0523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='load',
            old_name='destionation_city',
            new_name='destination_city',
        ),
    ]
