# Generated by Django 2.1.7 on 2019-04-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0004_auto_20190429_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='pickup_date',
            field=models.DateField(),
        ),
    ]
