# Generated by Django 2.1.7 on 2019-03-27 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0004_remove_load_pickup_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load',
            name='suggested_price',
        ),
    ]
