# Generated by Django 2.1.7 on 2019-04-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0005_remove_load_suggested_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrier',
        ),
        migrations.AddField(
            model_name='load',
            name='pickup_date',
            field=models.DateTimeField(default=None),
        ),
    ]
