# Generated by Django 2.1.7 on 2019-04-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0006_auto_20190408_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='pickup_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
