# Generated by Django 2.1.7 on 2019-04-10 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190410_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shipper',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipper_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
